### ISSUE TITLE
Build directory not purged

### ISSUE THREAD

**Issue by tejaycar** [wohali/couchdb-cookbook#32]
https://github.com/wohali/couchdb-cookbook/blob/master/recipes/source.rb#L70 untar's the source tarball.  We then run `make` and `make install`, however, we leave the resulting build directory in place.  As a result, if a change is later made (such as a new version of erlang), the recipe will not properly re-compile from source.  If a final cleanup line were added to the `install couchdb` execute resource, it would solve the problem.

```
cd /tmp && rm -Rf #{Chef::Config[:file_cache_path]}/apache-couchdb-#{node['couch_db']['src_version']}
```

**Comment by wohali** [comment]
Sorry to be so late on this. I've added the request in https://github.com/wohali/couchdb-cookbook/commit/6697f59196d2e181723770cc1eccb807d88d5337
