### ISSUE TITLE
couchdb 2.0

### ISSUE THREAD

**Issue by Jimflip** [wohali/couchdb-cookbook#33]
So what are the plans for this cookbook and couchdb 2.0?
Will this be expanded to support the new version, including clustering or a fresh cookbook focusing on the new couchdb?

**Comment by wohali** [comment]
Hey @Jimflip Sorry for the delay. I've finally found sponsorship to update the cookbook for 2.0 and beyond. A new release should be forthcoming shortly. I will do one final release to support the 1.x versions.

**Comment by wohali** [comment]
Done!
