### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by maoueh** [wohali/couchdb-cookbook#37]
Hi @wohali,

It's just to ask for a proper release of version 2.5.3 when you have some free time. Current release is now a year old and current `master` contains some nice to have fixes like:
- #35 
- #26 
- #28 
- #24 

No rush here.

Thanks in advance and regards,
Matt

**Comment by acoulton** [comment]
:+1: it would be great to have a new release if possible.

**Comment by maoueh** [comment]
ping @wohali 

I could also handle the future of this cookbook if you add me as a maintainer of this repository and grants me some access for me to upload the cookbook to supermarket.

**Comment by maoueh** [comment]
ping @wohali

**Comment by wohali** [comment]
So very srry for the delay here. I've not been using Chef for my job for a while now, so this got backburnered. And attempts to get a new contributor involved didn't pan out, either.

I finally have a sponsor to help get a CouchDB 2.0 version of this cookbook out the door, so I'm going to do one final 1.x-compatible release this week.

**Comment by wohali** [comment]
Done!
